libretro/tyrquake

common/common.h, common/d_polyse.c, common/draw.c, common/host.c, common/libretro.c, common/model.c, common/r_light.c, common/r_local.h, common/r_surf.c, common/vid.h
Pros
+ loads .LIT files
+ uses a 18-bit color lookup table for precision
+ maps display in a colorful light with faithful luminance range (depending on your .lit file)
Cons
- no proper model lighting currently
- no cvar/option to turn it off currently
- dynamic lights look dark orange (must be Tyrquake's doing, left over from GL)
- can be slow on some systems.  I do not know if this would toast a wii or a psp
=> Initial colored lighting support

common/libretro.c
Tyrquake fails to load the pak files or either of the two expansions without full paths.
Does not work:
`retroarch -L /usr/lib64/libretro/tyrquake_libretro.so pak0.pak`
`retroarch -L /usr/lib64/libretro/tyrquake_libretro.so rogue/`
`retroarch -L /usr/lib64/libretro/tyrquake_libretro.so hipnotic/`
Does work:
`retroarch -L /usr/lib64/libretro/tyrquake_libretro.so quake/`
`retroarch -L /usr/lib64/libretro/tyrquake_libretro.so /full/path/to/quake/rogue`
`retroarch -L /usr/lib64/libretro/tyrquake_libretro.so /full/path/to/quake/hipnotic`
This pull request will fix the first 3 examples. It still might be missing something, but its better than nothing. It will still not be able to start the rogue or hipnotic pak files directly which is not really a big problem when `retroarch -L …
=> Fix loading tyrquake from a terminal without full paths

common/libretro.c
This will allow binding L2 and R2 to something useful in Tyrquake. They will be bound to Look down (PGDN) and Look up (DEL) by default.
=> Add L2 and R2 support to the libretro joypad

Makefile, common/libretro.c, jni/Android.mk
This patch makes this core report the git version along with its library_version. This is important because otherwise it is impossible to replicate a build without extra knowledge, and things like Netplay that demand versions be the same can't be reliably known to work.
=> Report git version with library_version

Makefile.common, common/snd_codec.c, libretro-common/compat/compat_strl.c, libretro-common/include/retro_assert.h
Fixes: https://github.com/libretro/tyrquake/issues/32
=> libretro: Fix undefined symbol strlcpy

common/libretro.c
Couldn't move in menu before when core control used mouse/keyboard.
Corrected some broken indentation.
=> add missing menu keys for mouse/kb control

common/libretro.c
On Raspberry Pi 3, lr-tyrquake core crashes with "Illegal instruction" error. Problem was traced to commit https://github.com/libretro/tyrquake/commit/2b0c9f232a9505862f10abc45558c0703a9d30b8
Debugging the issue led to the discovery of gp_layouts[2].name erroneously returning the contents of the "layouts" string.
=> Fix crash due to array access out of bounds

common/libretro.c
Handling keyboard keys twice cause the core to behave as if the keys
were immediately released.
=> Keyboard callback fixes

common/menu.c
The existing core has the in-game video option 'Smooth Animation', which enables/disables linear interpolation for character animations (it sets 'r_lerpmodels' to 1 or 0). It doesn't, however, enable/disable linear interpolation for character *movement* - this is set by a different cvar ('r_lerpmove').
The result is that you can turn 'Smooth Animation' on, and the enemies still jerk around in horrible fashion. It looks like they are 'teleporting' from step to step. Setting both 'r_lerpmodels' and 'r_lerpmove' to zero is fine if you want an authentic Quake experience, but if you set one of them to 1 then you should probably set the other to 1 as well...
This trivial pull request just adds an additional 'Smooth Movement' setting to the in-game video menu, so users can set 'r_lerpmove' to 1 …
=> Add 'Smooth Movement' to in-game video options menu

common/libretro.c
This pull request allows the analog deadzone to be configured via the core options interface. This makes the core usable with old xbox 360 gamepads, which are notoriously prone to analog stick drift.
While I was adjusting the controls, I also took the opportunity to remap a useless button in the 'modern' controller layout...
Previously, 'select' was set to toggle the console. This had no real value, since to use the console in any meaningful fashion requires a keyboard - and if you have a keyboard, there are already 3 keys you can press to toggle the console. I have modified 'select' so that it now shows the current scores, so users can easily see how many monsters/secrets are remaining (I think this is far more useful in a gamepad-only/console-type environment).
=> Add analog deadzone to core options + remap useless controller button

common/common.c, common/common.h, common/console.c, common/host.c, common/host_cmd.c, common/libretro.c, common/menu.c, common/quakedef.h
The existing core writes the Quake 'config.cfg' + save files to the actual game directory. This is *not good*, for the following reasons:
- It doesn't follow the RetroArch standard of writing save files to the frontend-defined save directory.
- It makes it a nuisance to backup/restore game saves. With other cores, all saves are in one place and can easily be archived and shared across different machines. With the current tyrquake core, one has to grub around in individual game directories and pick out specific files.
- It means the game data has to be kept on writeable storage. This is a significant problem on Android devices, where internal storage is limited and it is often desirable to place large roms on an 'external' micro SD card - which in many cases cannot be written to by user …
=> Move core-generated files (config + saves) to frontend-defined save directory

common/libretro.c
Fix https://github.com/libretro/tyrquake/issues/65
=> fix kb/mouse directions not working in menu

Makefile, common/mathlib.c
add flag for ios-arm64 since it does not have neon instructions
=> iOS: support for building using buildbot recipe

Makefile
Adds support for easily building for Raspberry Pi 4 in 64bit mode. There is already a Raspberry Pi OS BETA (formerly Raspbian) with 64bit kernel and libs, and that's what the Pi4 will use as default at some point.
=> Add Raspberry Pi 4 64bit platform.

common/host.c, common/libretro_core_options.h
Allow high framerate, warn about it in core options.
Didn't see much problems with 120fps playing several levels, even with traps in them.
=> Allow high framerate.

common/alias_model.c, common/d_fill.c, common/d_polyse.c, common/d_scan.c, common/d_surf.c, common/mathlib.c, common/mathlib.h, common/model.h, common/net.h, common/net_udp.c, common/r_alias.c, common/r_edge.c, common/r_main.c, common/r_part.c, common/r_surf.c
As reported here: https://github.com/libretro/tyrquake/pull/108#issuecomment-954777618, the core segfaults under some circumstances when running the shareware version of Quake on Windows.
It turns out that the code makes a number of assumptions about the width of certain data types when casting pointers, which are not true on a number of platforms. On 64bit Windows this can cause pointer addresses to be determined incorrectly - leading to chaos.
This PR fixes the issue by using standard fixed-width types for the affected pointer casts. It also cleans up some other related compiler warnings.
=> Improve type safety when casting pointers

common/libretro_core_options.h
On recent versions of RetroArch the core options are currently falling back to v0 format (missing sublabels) due to a trivial 'supported version check' error in `libretro_core_options.h`. This PR fixes the issue.
=> Fix core options version detection

QW/client/quakedef.h, QW/qwfwd/qwfwd.c, QW/server/qwsvdef.h, common/cd_common.c, common/cd_linux.c, common/cl_parse.c, common/common.c, common/common.h, common/quakedef.h, common/shell.c, common/spritegn.h
On some systems, including stdio.h can add quite a bit to the binary size. This include is now unnecessary either way.
=> remove stdio includes

common/common.c, common/d_sprite.c, common/r_sprite.c
This PR fixes three sources of memory leaks in the core:
- A relatively minor one related to loading PAK files (the file handle was always left open)
- Two serious ones in the sprite handling code, which may potentially trigger multiple times per frame (and which were likely to cause crashes on RAM limited platforms...)
=> Fix memory leaks

common/libretro.c, common/snd_mix.c
PR #93 'fixed' audio at low framerates by dynamically reducing the output sample rate (reducing the quality - quite substantially - but at least producing something). It turns out that this was the wrong fix; audio was breaking at low framerates due to a *frontend* (RetroArch) limitation, whereby samples were being discarded due to the audio batch callback being used to send more frames than it could deal with.
This PR reworks the core such that audio is handled in the same way as vitaquake2. Arbitrary numbers of samples per frames are now supported, and usage of the audio batch callback is minimised whenever possible. Consequently, sample rate 'scaling' is no longer required (greatly improving audio quality at low framerates).
In addition, the default audio sample rate has been reduced …
=> Audio improvments + minor fixes

common/libretro.c
At present, when the `Framerate` core option is set to `Auto` the framerate value is read directly from the frontend. This is a problem because the internal audio generation only works correctly at specific framerates - certain non-integer values cause resampling artefacts/crackling.
This PR sanitises the framerate read from the frontend, choosing the nearest value from the allowed framerate whitelist.
=> Ensure that only valid framerates are selected when 'Framerate' core option is set to 'Auto'

common/libretro_core_options.h
Added 384x216 resolution, so we can have a fullscreen, pixel-perfect experience at both 1920x1080 (Full HD) and 3840x2160 (4K).
Note: for this to work, the aspect ratio "Full" must be set in Settings -> Video -> Scaling.
=> Added 384x216 resolution

common/net.h, common/net_dgrm.c, common/net_main.c, common/qtypes.h
- Fixes #134
When compiling with -std=c23 the following errors are observed.
common/qtypes.h:37:15: error: cannot use keyword 'false' as enumeration constant
37 | typedef enum{ false, true, ENSURE_INT_QBOOL = 0x70000000 } qboolean;
|               ^~~~~
common/qtypes.h:37:23: error: cannot use keyword 'true' as enumeration constant
37 | typedef enum{ false, true, ENSURE_INT_QBOOL = 0x70000000 } qboolean;
|                       ^~~~
common/net_main.c:869:9: error: too many arguments to function 'pp->procedure'; expected 0, have 1
869 |         pp->procedure(pp->arg);
|         ^~            ~~~~~~~
common/net.h:320:12: note: declared here
320 |     void (*procedure) ();
|            ^~~~~~~~~
common/net_main.c:112:56: error: initialization of 'void (*)(void *)' from incompatible pointer …
=> Allow compile with -std=c23
